apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-fiber-app-deployment
spec:
  selector:
    matchLabels:
      app: my-fiber-app
  template:
    metadata:
      labels:
        app: my-fiber-app
    spec:
      containers:
        - name: my-fiber-app
          image: fiber-app
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: fiber-secret
                  key: host
            - name: DB_PORT
              value: '5432'
            - name: DB_NAME
              value: 'fiber'
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: fiber-secret
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fiber-secret
                  key: password

          imagePullPolicy: Never
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: my-fiber-app-service
spec:
  type: LoadBalancer
  selector:
    app: my-fiber-app
  ports:
    - port: 3000
      targetPort: 3000